name: "Security Scanning"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  dependency-check:
    name: "Dependency Vulnerability Scan"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        pip install -r requirements.txt
        
    - name: Run Safety (Python dependency vulnerability scanner)
      continue-on-error: true
      run: |
        safety check --json --output safety-report.json || echo '{"vulnerabilities": [], "scanned_packages": []}' > safety-report.json
        
    - name: Run Bandit (Python security linter)
      continue-on-error: true
      run: |
        bandit -c .bandit -r src/ -f json -o bandit-report.json || true
        bandit -c .bandit -r src/ -f txt
        
    - name: Upload Safety report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: safety-report
        path: safety-report.json
        
    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-report
        path: bandit-report.json

  container-security:
    name: "Container Security Scan"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t bitaxe-monitor:security-test .
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'bitaxe-monitor:security-test'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  secret-scan:
    name: "Secret Detection"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Run TruffleHog OSS
      continue-on-error: true
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --debug --only-verified